name: Interactive BOMs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      - uses: wlcx/kicad-interactive-html-bom@main
        name: Run kicad site generator
      - uses: actions/upload-artifact@v2
        name: Upload artifacts
        with:
          name: site
          path: out/*
      - uses: actions/upload-pages-artifact@v1
        name: Upload pages artifact
        with:
          path: out/
          
  # Deploy job
  deploy:
    needs: generate

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
